### ISSUE TITLE
Make api return dictionaries, not raw responses

### ISSUE THREAD

**Issue by AverageS** [TheHive-Project/TheHive4py#12]
#### Feature Request
I think it would be great to incapsulate responses. Right now API object returns raw responses and responses most of the times contain json. Why not return pretty dictionaries? It would simplify the work with api, when user often has to do json.loads().

**Comment by nadouani** [comment]
Hi @AverageS yes this is under progress, we will create a wrapper around the TheHiveApi class

**Comment by AverageS** [comment]
How can i help you? Are there any road maps?  I'm looking forward to use TH and enhance api i think it could be helpful  for you.

**Comment by nadouani** [comment]
The goal of TheHive4Py is to make the APIs exposed by TheHive, easier to call. The current version is really basic and can definitely be improved. If you are looking to improve it, then this is great.

What we can do is to make sure to track features to be added (by creating the corresponding issues on github) and start writing code :)

If you are familiar with python then, your help is welcome.

We don't have a specific roadmap for this library but we try to implement the features that users ask for. So it's open, and good ideas are welcome too.

This issue is one of the improvements that could help developers use TheHive4Py when they have to integrate TheHive with external tools or scripts

**Comment by npratley** [comment]
I have started some work in this area so am happy to take this issue on. I expect the resulting interface to use the objects from models.py rather than passing around dictionaries but the effect is the same - abstract away the Requests response objects.

**Comment by nadouani** [comment]
This will be fixed via #85
