### ISSUE TITLE
Add find_task_logs function

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive4py#160]
### Request Type
Feature Request

### Problem Description
This function allows searching for task logs

**Comment by jnahorny** [comment]
@nadouani I've found this issue when searching for a solution, after I've discovered `get_task_logs()` method only returns 10 results, with no option to change it.

I already wrote the version that behaves just like `get_case_tasks()` (allows you to pass params and additional query criteria).
I would happily sent it as a pull request, just want to discuss one thing -- name of the method.
I believe this should replace existing `get_task_logs()` implementation, for the sake of naming consistency.
I mean, if `get_case_tasks()` returns *all* the tasks, why does `get_task_logs()` not return all the logs? I'd say it's even more useful, as I think there's higher probability of having > 10 log entries in a task, than having > 10 tasks in the case. Isn't it?
Also, this woudn't break compatibility, because if you don't provide params, nor query, you'd call the method exactly the way it is now.

But, if you prefer other name (`find_task_logs()`?), and you want to keep existing `get_task_logs()` as is, I'm OK with that as well.

Thank you!

**Comment by jnahorny** [comment]
I had to delete the original PR, because I've messed something up when doing the rebase. This issue is now addressed in the following PR: https://github.com/TheHive-Project/TheHive4py/pull/200

**Comment by nadouani** [comment]
Hello @jnahorny https://github.com/TheHive-Project/TheHive4py/pull/200 is perfect.

could you provide two functions:
- `find_tasks_logs(**attributes)`: generic function to search for logs
- `get_task_logs(task_id, **attributes)` that calls `find_tasks_logs by specifying the `ParentId` criteria

If you don't have time, I can make it too by using your PR.

**Comment by jnahorny** [comment]
> Hello @jnahorny #200 is perfect.
> 
> could you provide two functions:
> 
> * `find_tasks_logs(**attributes)`: generic function to search for logs
> * `get_task_logs(task_id, **attributes)` that calls `find_tasks_logs` by specifying the `ParentId` criteria
> 
> If you don't have time, I can make it too, using your PR.

@nadouani  It's not that I don't have time, but I'm not sure how to do it. I guess it would be probably faster for you to do it, instead of explaining to me how to do it. But I'm open to both scenarios :)

**Comment by nadouani** [comment]
Sounds good, I'll do it using your PR ;)

**Comment by jnahorny** [comment]
> Sounds good, I'll do it using your PR ;)

Thank you! I can't wait for it to be in production!

**Comment by nadouani** [comment]
@jnahorny take a look to [b009365](https://github.com/TheHive-Project/TheHive4py/commit/b009365b02d46414e770fa14abd4b21440eaea02) to understand what I meant.

Thanks for your contribution
