### ISSUE TITLE
TheHiveApi.find_alerts cannot find alerts with specific custom field

### ISSUE THREAD

**Issue by wloody54** [TheHive-Project/TheHive4py#209]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10, Ubuntu
| TheHive4py 1.8.1   | 

### Problem Description
When I am using find_alerts with specific customField in query, the result is empty. I tried find_cases and API request and both works without problem.

Steps to Reproduce: in attach files
![find_cases](https://user-images.githubusercontent.com/46425280/105035201-e4603980-5a5a-11eb-84f1-ae6650948995.jpg)
![find_alerts](https://user-images.githubusercontent.com/46425280/105035212-eaeeb100-5a5a-11eb-9cc1-754de0a65193.jpg)
![API](https://user-images.githubusercontent.com/46425280/105035213-eb874780-5a5a-11eb-9036-001260eb4dd5.jpg)

**Comment by CapaoAzul** [comment]
+1

**Comment by CapaoAzul** [comment]
+1
I have updated my thehive for the v4 and I am using thehive4py 1.8.1.
Since thehive update, the query with In("customFields.client.string", CLIENT) does not retrieve anything, but I am sure there are alerts.
CLIENT is an array
The query worked before, maybe there is some change that I have to do for the new version...

**Comment by mnmnc** [comment]
@wloody54 your query in curl is wrong. 
Look at the example in code: 
![image](https://user-images.githubusercontent.com/7818126/108406257-7443ff80-7222-11eb-8c4a-2eeb6a9eb4e3.png)

@CapaoAzul yours is also wrong.
Shoud look like `In(customFields.client.string", [CLIENT])`

Because second argument for `In` should be an array.

**Comment by CapaoAzul** [comment]
My code is equal. The datatype is "customFields.client.string" and the CLIENT is an array.

I think the problem is datatype being a customField
