### ISSUE TITLE
Pytest: Issues when running it

### ISSUE THREAD

**Issue by LetMeR00t** [TheHive-Project/TheHive4py#284]
Hello,
Just to make sure that I'm not making any mistake on my side but I catched some errors on your current configuration for pytest:

1) It should be clearly described in your documentation that Docker need to be installed before doing anything with pytest (avoid to loose some time)
2) When you create the container, you create it with "-p 9000" which is creating the docker on a random port (on my side, the internal port 9000 of the container was exposed on the external port 56432 which is random and so your tests can't work as it's trying to reach the port 9000, it should be better to use "-p 9000:9000" right ? Did you have any issue on your side ?
3) When trying to download the image from the repository, it fails as "thehive4py-thehive:5.0.23" isn't a right repository. Using "strangebee/thehive:5.0.23" instead is working, do you confirm ?
4) Once I have a container setup and working, all tests are failing because the organization isn't found:
```
================================================================================================================================================= short test summary info =================================================================================================================================================
ERROR tests/test_alert_endpoint.py::TestAlertEndpoint::test_create_and_get - thehive4py.errors.TheHiveError: NotFoundError - Organisation not found
ERROR tests/test_alert_endpoint.py::TestAlertEndpoint::test_update - thehive4py.errors.TheHiveError: NotFoundError - Organisation not found
ERROR tests/test_alert_endpoint.py::TestAlertEndpoint::test_bulk_update - thehive4py.errors.TheHiveError: NotFoundError - Organisation not found
ERROR tests/test_alert_endpoint.py::TestAlertEndpoint::test_follow_and_unfollow - thehive4py.errors.TheHiveError: NotFoundError - Organisation not found
[...]
```
Do you have the same issue ?

As those things are basic stuff from pytest, it's really weird to have such issues so I want to make sure that I'm not doing something wrong. I can help to fix such issues in a defined patch if it's confirmed that there are issues and not a misconfiguration from my side.

Thank you

**Comment by Kamforka** [comment]
Hey @LetMeR00t to quickly address your questions.

Everything you discovered is correct, the tests using a private prebaked image called `thehive4py-thehive:xxx`. This image is not yet available to public as we are still under discussion with the core TheHive team on how to finalize it.
It is prebaked, because it has users and organisations already set up for the tests, and also it has a full fledged platinum license activated in it (which is causing the most issues as that must not be publicly distributed).
The test setup is creating a container using the above mentioned image on a random port but with a static name, and then using the name to look for the container for tests later on.

There is a still pending PR which is attempting to refactor the test configuration to be easier to manage (https://github.com/TheHive-Project/TheHive4py/pull/276), but the main issue is coming from the prebaked image and the licensing.

Therefore at the moment the test suite is not available for public usage, and probably in the future its usage will still be restricted to github actions.

Hope that helps reducing the confusion!

**Comment by LetMeR00t** [comment]
Hi 
Thank you for the clarification but if I need to push any feature with the corresponding tests, how can I manage that with your pytest to test it and provide everything you need ? 
Can’t we have a different environment for testing purposes on the public interface ? It should be straight forward to have something setup with a fake organisation, users, cases etc …
Thank you

**Comment by Kamforka** [comment]
Well the prebaked image is needed just for that.
An instance without a valid license is read only, so you can only test read only operations and you have a huge limitation on the accessible endpoints too.

I have my own licensed version which is regularly revalidated by StrangeBee, but at the moment it is a manual process and work in progress.

**Comment by LetMeR00t** [comment]
But not everything is under the licence right ? Most of the features can be used without any licence so we could have a specific environment to support that … 
Is it something you want to offer or not at all at the end ? Because again how can I created a test and push any PR?

**Comment by Kamforka** [comment]
Without a license you have a read only environment basically. In my opinion that is useless.With a private but licensed image at least you can have tests in the GitHub actions.I agree that this is still not the most convenient solution, but at least it is something.With a community license you can work something out. But the challenge remains the same. At the moment licensing is a manual process, supervised by StrangeBee. So first we need to work out a process with them.Hope you understand!On 1 Jun 2023 12:29, LmR ***@***.***> wrote:
But not everything is under the licence right ? Most of the features can be used without any licence so we could have a specific environment to support that …
Is it something you want to offer or not at all at the end ? Because again how can I created a test and push any PR?

**Comment by Kamforka** [comment]
Closing this in favor of #292
